<?php require 'templates/layout/header.phtml' ?>

<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>

<form method='post' action='login'>
    <div class='form-group'>
    <div class='form-group'>
        <label for='name'>Name</label>
        <input type='name' class='form-control' id='name' name='nombre' required>
    </div>
        <label for='email'>Email</label>
        <input type='email' class='form-control' id='email' name='email' required>
    </div>
    <div class='form-group'>
        <label for='password'>Password</label>
        <input type='password' class='form-control' id='password' name='password' required>
    </div>
    <button type='submit' class='btn btn-primary mt-3'>Login</button>
</form>
<a class='btn btn-gray mt-2 mb-5' href="signIn">Sign in</a>
<?php require 'templates/layout/footer.phtml' ?>

